/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instituto_francisco;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Daniel Pinzón
 */
public class MiVentanaBase extends JFrame implements ActionListener {

    /**
     * Creates new form MiVentanaBase
     */
    JPanel contentPane;
    public MiVentanaBase(String titulo, int ancho, int alto) {
        super(titulo);
        contentPane = (JPanel) this.getContentPane();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //Centrar la ventana....
        
        Dimension t_pantalla= Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = (t_pantalla.width/2) -(ancho/2);
        int y = (t_pantalla.height/2) -(alto/2);
        setBounds(x, y, ancho, alto);
        
        initComponents();
        
        bBnimbus.addActionListener(this);
        bMetal.addActionListener(this);
        bMotif.addActionListener(this);
        bWindows.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bG_Skins = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bMetal = new javax.swing.JRadioButtonMenuItem();
        bMotif = new javax.swing.JRadioButtonMenuItem();
        bWindows = new javax.swing.JRadioButtonMenuItem();
        bBnimbus = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        bSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Look&Feel");

        bG_Skins.add(bMetal);
        bMetal.setSelected(true);
        bMetal.setText("Metal (Java)");
        bMetal.setName("bMetal"); // NOI18N
        jMenu1.add(bMetal);

        bG_Skins.add(bMotif);
        bMotif.setText("Motif (Unix)");
        bMotif.setName("bMotif"); // NOI18N
        jMenu1.add(bMotif);

        bG_Skins.add(bWindows);
        bWindows.setText("Windows");
        bWindows.setName("bWindows"); // NOI18N
        jMenu1.add(bWindows);

        bG_Skins.add(bBnimbus);
        bBnimbus.setText("Bnimbus");
        bBnimbus.setName("bBnimbus"); // NOI18N
        jMenu1.add(bBnimbus);
        jMenu1.add(jSeparator1);

        bSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bSalir.setText("Salir");
        bSalir.setName("bSalir"); // NOI18N
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jMenu1.add(bSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
       salir();
    }//GEN-LAST:event_bSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         salir();
    }//GEN-LAST:event_formWindowClosing


    public void cambiaLF(ActionEvent e){
       String tipoVista;
       
       if( e.getSource()== bMotif ){
            tipoVista="com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        }else if (e.getSource()== bMetal )
            tipoVista="javax.swing.plaf.metal.MetalLookAndFeel";
        else if (e.getSource()== bWindows )
                tipoVista="com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
                else
                    tipoVista="javax.swing.plaf.nimbus.NimbusLookAndFeel";
        try {
            UIManager.setLookAndFeel(tipoVista);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            System.out.println("Error al cambiar de Apariencia :"+ e.toString());
        }
        
       contentPane.updateUI();
    
    }
    //-----------------------------------------------------
    //--- metodo Salir------------------------------------------------------------------
    public void salir(){
        int res= JOptionPane.showConfirmDialog(null,"¿Quieres salir?",
                                                    "Cerrando Aplicación",
                       JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
               if(res==JOptionPane.YES_OPTION){
                            //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                              System.exit(0);
                          }  
               else  { this.setVisible(true);
               }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem bBnimbus;
    private javax.swing.ButtonGroup bG_Skins;
    private javax.swing.JRadioButtonMenuItem bMetal;
    private javax.swing.JRadioButtonMenuItem bMotif;
    private javax.swing.JMenuItem bSalir;
    private javax.swing.JRadioButtonMenuItem bWindows;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        cambiaLF(e);
        
    }
}
